import {vocabulary,accepts,shuffle} from './vocabulary.js';
import {drawScene} from './scene.js';
const $=id=>document.getElementById(id);
const stages=[{key:'rocks',count:10,title:'10 büyük taş yolu kapatıyor!',task:'Bir kelime çöz, bir taşı kaldır.',name:'TAŞLI GEÇİT'}, {key:'lava',count:10,title:'Önünde kızgın lavlar var!',task:'Her kelimeyle güvenli bir geçiş taşı yerleştir.',name:'LAV VADİSİ'}, {key:'river',count:10,title:'Nehirden geçmek için köprü kur!',task:'Doğru cevaplarla köprüyü tamamla.',name:'NEHİR GEÇİŞİ'}, {key:'tire',count:8,title:'Eyvah, lastik patladı!',task:'Kelimeleri çözerek lastiği onar.',name:'TAMİR MOLASI'}, {key:'fuel',count:7,title:'Benzin bitti, hazine çok yakın!',task:'Her doğru cevapla depoya yakıt ekle.',name:'SON DURAK'}];
let state=null, audio=null,sound=false,animation=null;
function beep(ok=true){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=ok?660:180;g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.start();o.stop(audio.currentTime+.2);}catch{}}
function show(id){for(const n of ['menu','game','end'])$(n).hidden=n!==id;window.scrollTo({top:0,behavior:'instant'});}
function stageInfo(){let offset=0;for(let i=0;i<stages.length;i++){if(state.index<offset+stages[i].count)return{...stages[i],number:i+1,done:state.index-offset};offset+=stages[i].count;}return{...stages[4],number:5,done:7};}
function start(mode){cancelAnimationFrame(animation);state={mode,lives:mode===3?7:5,index:0,words:shuffle(vocabulary),wrong:new Map(),locked:false,travel:0};show('game');$('modeLabel').textContent=mode===3?'Türkçe → İngilizce · Şıksız':`İngilizce → Türkçe · ${mode===1?'Şıklı':'Şıksız'}`;renderQuestion();}
function renderQuestion(){state.locked=false;const s=stageInfo(),word=state.words[state.index];$('lives').textContent='♥'.repeat(state.lives);$('lives').setAttribute('aria-label',`${state.lives} can`);$('progressText').textContent=`${state.index} / 45 kelime`;$('bar').style.width=`${state.index/45*100}%`;$('obstacleLabel').textContent=`BÖLÜM ${s.number} / 5 · ${s.name}`;$('task').textContent=s.title;$('instruction').textContent=s.task;$('sceneBadge').textContent=`${s.name} · ${s.done} / ${s.count}`;$('word').textContent=state.mode===3?word.tr:word.en;$('speak').hidden=state.mode===3;$('feedback').textContent='';$('feedback').className='';$('next').hidden=true;$('choices').replaceChildren();$('choices').hidden=state.mode!==1;$('answerForm').hidden=state.mode===1;$('answer').value='';$('answer').disabled=false;$('answerForm').querySelector('button').disabled=false;$('answerLabel').textContent=state.mode===3?'İngilizce karşılığını yaz':'Türkçe karşılığını yaz';$('answer').placeholder=state.mode===3?'English word…':'Türkçe anlamı…';
 if(state.mode===1){const options=shuffle([word,...shuffle(vocabulary.filter(w=>w.id!==word.id)).slice(0,2)]);options.forEach((w,i)=>{const b=document.createElement('button');b.textContent=`${'ABC'[i]}  ·  ${w.tr}`;b.onclick=()=>submit(w.id===word.id);$('choices').append(b);});}else $('answer').focus();draw();}
function draw(){if(state)drawScene($('world'),{obstacle:stageInfo().key,cleared:stageInfo().done,travel:state.travel,time:performance.now()/1000});}
function submit(correct){if(state.locked)return;const word=state.words[state.index];beep(correct);if(correct){state.locked=true;$('feedback').className='good';$('feedback').textContent='Doğru! Yol biraz daha açıldı. ✦';$('next').hidden=false;for(const b of $('choices').children)b.disabled=true;$('answer').disabled=true;$('answerForm').querySelector('button').disabled=true;$('next').focus();}else{state.lives--;state.wrong.set(word.id,word);$('lives').textContent='♥'.repeat(state.lives);$('lives').setAttribute('aria-label',`${state.lives} can`);$('feedback').className='bad';$('feedback').textContent=`Bir can azaldı. Doğru cevap: ${state.mode===3?word.en:word.tr}. Tekrar dene.`;if(!state.lives){state.locked=true;finish(false);}}}
function next(){if(!state.locked)return;$('next').hidden=true;let begun=performance.now();function frame(t){state.travel=Math.min((t-begun)/750,1);draw();if(state.travel<1)animation=requestAnimationFrame(frame);else{state.travel=0;state.index++;if(state.index===45)finish(true);else renderQuestion();}}animation=requestAnimationFrame(frame);}
function finish(won){cancelAnimationFrame(animation);show('end');$('endIcon').textContent=won?'🏆':'🧭';$('endTag').textContent=won?'GÖREV TAMAMLANDI':'YENİ BİR DENEME, YENİ BİR MACERA';$('endTitle').textContent=won?'Hazineyi buldun!':'Maceraya kısa bir mola.';$('endText').textContent=won?`45 kelimenin tamamını çözdün, bütün engelleri aştın! ${state.lives} canla hazineye ulaştın.`:`Canların bitti. ${state.index} / 45 kelimeyi çözdün. Öğrendiğin kelimelerle yeniden yola çıkabilirsin.`;$('review').replaceChildren();if(state.wrong.size){const details=document.createElement('details'),summary=document.createElement('summary'),ul=document.createElement('ul');summary.textContent=`Tekrar çalışabileceğin kelimeler (${state.wrong.size})`;for(const w of state.wrong.values()){const li=document.createElement('li');li.textContent=`${w.en} → ${w.tr}`;ul.append(li);}details.append(summary,ul);$('review').append(details);}}
function home(){cancelAnimationFrame(animation);state=null;show('menu');preview();}
function preview(){drawScene($('preview'),{preview:true,time:0});}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(Number(b.dataset.mode)));$('home').onclick=home;$('endHome').onclick=home;$('retry').onclick=()=>start(state.mode);$('next').onclick=next;$('answerForm').onsubmit=e=>{e.preventDefault();if($('answer').value.trim())submit(accepts($('answer').value,state.words[state.index],state.mode));};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫ Ses kapat':'♫ Ses aç';$('sound').setAttribute('aria-pressed',String(sound));beep();};$('speak').onclick=()=>{if('speechSynthesis'in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(state.words[state.index].en);utterance.lang='en-GB';utterance.rate=.8;speechSynthesis.speak(utterance);}};window.addEventListener('resize',()=>state?draw():preview());preview();
